#ifndef VERSION_H_INCLUDED
#define VERSION_H_INCLUDED

#define CMAKE_PROJECT_VERSION_MAJOR "0"
#define CMAKE_PROJECT_VERSION_MINOR "1"
#define CMAKE_PROJECT_VERSION_PATCH "2"

#endif /* VERSION_H_INCLUDED */
