on:
  workflow_dispatch:

name: Test Workflow

jobs:
  
  build:
    name: Build Upload Release
    runs-on: ubuntu-latest
    steps:
      - name: Echo info
        run: echo "Trying to use mingw"

      - name: Mingw
        run: mingw-w64 --help
